import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import StepsBullets from '../components/bulletList';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Step1({ children, step }: { children: React.ReactNode; step: string }) {
  return (
    <div className={`${inter.className} w-full flex`}>
      <div className="w-1/3">
        <StepsBullets step={'step1'} />
      </div>
      <div className="w-2/3">{children}</div>
    </div>
  );
}
